import type { CatalogTshirt } from "./types";
import { COLOR_MAP } from "./designs";

/**
 * Placeholder catalog. Using Unsplash URLs for now so the shop
 * actually looks like a shop. Any dead link just falls back to the
 * SVG mockup, so we don't get broken image icons.
 *
 * When the real product shoots are done:
 *   1. dump them in `public/tees/` (e.g. public/tees/tee-dragon-black.jpg)
 *   2. set `imageUrl: "/tees/tee-dragon-black.jpg"` on the matching row
 * Local paths skip the `remotePatterns` rule in next.config.ts.
 *
 * @var CatalogTshirt[]
 */
const UNSPLASH = (id: string, w = 800) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&auto=format&fit=crop&q=80`;

// Grab bag of tee photos keyed by color. Messy on purpose —
// easier to swap out one by one later.
const PHOTOS = {
  black: UNSPLASH("1583743814966-8936f5b7be1a"),
  blackAlt: UNSPLASH("1618354691373-d851c5c3a990"),
  white: UNSPLASH("1521572163474-6864f9cf17ab"),
  whiteAlt: UNSPLASH("1503341504253-dff4815485f1"),
  navy: UNSPLASH("1542272604-787c3835535d"),
  gray: UNSPLASH("1576566588028-4147f3842f27"),
  red: UNSPLASH("1527719327859-c6ce80353573"),
  green: UNSPLASH("1618354691373-d851c5c3a990"),
  pink: UNSPLASH("1503342394128-c104d54dba01"),
  yellow: UNSPLASH("1434389677669-e08b4cac3105"),
  blue: UNSPLASH("1560769629-975ec94e6a86"),
  generic: UNSPLASH("1581655353564-df123a1eb820"),
};

export const CATALOG: CatalogTshirt[] = [
  {
    id: "tee-dragon-black",
    name: "Dragon Fire Tee",
    description: "Bold dragon graphic on a midnight black tee.",
    price: 499,
    color: COLOR_MAP["black"],
    designId: "dragon",
    placement: "front-center",
    imageUrl: PHOTOS.black,
  },
  {
    id: "tee-bear-forest",
    name: "Forest Bear Tee",
    description: "Chill bear on a forest green classic fit.",
    price: 449,
    color: COLOR_MAP["forest"],
    designId: "bear",
    placement: "front-center",
    imageUrl: PHOTOS.green,
  },
  {
    id: "tee-tiger-mustard",
    name: "Mustard Tiger",
    description: "Eye of the tiger, mustard mood.",
    price: 549,
    color: COLOR_MAP["mustard"],
    designId: "tiger",
    placement: "front-center",
    imageUrl: PHOTOS.yellow,
  },
  {
    id: "tee-wolf-gray",
    name: "Lone Wolf",
    description: "Heather gray comfort tee with a wolf.",
    price: 399,
    color: COLOR_MAP["heather-gray"],
    designId: "wolf",
    placement: "front-center",
    imageUrl: PHOTOS.gray,
  },
  {
    id: "tee-eagle-navy",
    name: "Eagle Navy",
    description: "Soaring eagle print on navy.",
    price: 599,
    color: COLOR_MAP["navy"],
    designId: "eagle",
    placement: "back-center",
    imageUrl: PHOTOS.navy,
  },
  {
    id: "tee-octopus-royal",
    name: "Deep Blue Octopus",
    description: "Royal blue tee with a big octopus print.",
    price: 579,
    color: COLOR_MAP["royal-blue"],
    designId: "octopus",
    placement: "back-center",
    imageUrl: PHOTOS.blue,
  },
  {
    id: "tee-skull-black",
    name: "Skull Classic",
    description: "Minimal skull, maximum attitude.",
    price: 399,
    color: COLOR_MAP["black"],
    designId: "skull",
    placement: "front-left-chest",
    imageUrl: PHOTOS.blackAlt,
  },
  {
    id: "tee-fire-red",
    name: "Fire Red",
    description: "Hot red tee with a blazing fire.",
    price: 459,
    color: COLOR_MAP["red"],
    designId: "fire",
    placement: "front-center",
    imageUrl: PHOTOS.red,
  },
  {
    id: "tee-lightning-white",
    name: "Lightning Bolt",
    description: "Clean white tee with a lightning chest print.",
    price: 359,
    color: COLOR_MAP["white"],
    designId: "lightning",
    placement: "front-left-chest",
    imageUrl: PHOTOS.white,
  },
  {
    id: "tee-star-pink",
    name: "Pink Star",
    description: "Soft pink tee with a star graphic.",
    price: 379,
    color: COLOR_MAP["pink"],
    designId: "star",
    placement: "front-center",
    imageUrl: PHOTOS.pink,
  },
  {
    id: "tee-heart-cream",
    name: "Heart Cream",
    description: "Cream colored tee with a classic heart.",
    price: 349,
    color: COLOR_MAP["cream"],
    designId: "heart",
    placement: "front-left-chest",
    imageUrl: PHOTOS.whiteAlt,
  },
  {
    id: "tee-mountain-olive",
    name: "Mountain Olive",
    description: "Olive green tee with a mountain range.",
    price: 529,
    color: COLOR_MAP["olive"],
    designId: "mountain",
    placement: "back-center",
    imageUrl: PHOTOS.green,
  },
  {
    id: "tee-wave-royal",
    name: "Big Wave",
    description: "Royal blue tee with an ocean wave.",
    price: 499,
    color: COLOR_MAP["royal-blue"],
    designId: "wave",
    placement: "back-center",
    imageUrl: PHOTOS.blue,
  },
  {
    id: "tee-sun-mustard",
    name: "Sun Worship",
    description: "Mustard tee with a smiling sun.",
    price: 389,
    color: COLOR_MAP["mustard"],
    designId: "sun",
    placement: "front-center",
    imageUrl: PHOTOS.yellow,
  },
  {
    id: "tee-rocket-black",
    name: "Rocket Black",
    description: "Launch pad ready rocket print.",
    price: 469,
    color: COLOR_MAP["black"],
    designId: "rocket",
    placement: "front-center",
    imageUrl: PHOTOS.black,
  },
  {
    id: "tee-crown-maroon",
    name: "Crown Maroon",
    description: "Royalty in maroon.",
    price: 559,
    color: COLOR_MAP["maroon"],
    designId: "crown",
    placement: "front-center",
    imageUrl: PHOTOS.red,
  },
  {
    id: "tee-diamond-lavender",
    name: "Lavender Diamond",
    description: "Lavender tee with a little diamond chest print.",
    price: 419,
    color: COLOR_MAP["lavender"],
    designId: "diamond",
    placement: "front-left-chest",
    imageUrl: PHOTOS.pink,
  },
  {
    id: "tee-pinas-white",
    name: "Proud Pinas",
    description: "Proudly Pinoy. Clean white tee.",
    price: 499,
    color: COLOR_MAP["white"],
    designId: "pinas",
    placement: "front-center",
    imageUrl: PHOTOS.white,
  },
  {
    id: "tee-manila-black",
    name: "Manila Nights",
    description: "MNL text graphic, late-night black.",
    price: 429,
    color: COLOR_MAP["black"],
    designId: "manila",
    placement: "front-center",
    imageUrl: PHOTOS.blackAlt,
  },
  {
    id: "tee-grind-red",
    name: "Daily Grind",
    description: "GRIND big text on red. For the hustlers.",
    price: 459,
    color: COLOR_MAP["red"],
    designId: "grind",
    placement: "back-center",
    imageUrl: PHOTOS.red,
  },
];
